system:
  domain: 'stage.advocat.fenux.fi'
database:
  username: 'root'
  password: 'gOyzhR'
  
feedback:
  recipient_emails:
    - 'nitinvi.dev@gmail.com'
    - 'juri.oshujev@fenux.fi'
    - 'ari.heiskanen@fenux.fi'
