class Setting < ApplicationRecord
	belongs_to :brand, inverse_of: :settings
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"
  belongs_to :updater, class_name: "User", foreign_key: "updater_id"

  enum lead_delivery_start_day: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]

  enum lead_delivery_end_day: ["END_MONDAY", "END_TUESDAY", "END_WEDNESDAY", "END_THURSDAY", "END_FRIDAY", "END_SATURDAY", "END_SUNDAY"]

  validates :brand, :presence => true

  def self.setting_keys
    keys = [ "COMMON_TAX_BASE", "REDUCED_TAX_BASE_1", "REDUCED_TAX_BASE_2", "TAX_FREE_SERVICE", "CO_OPERATIVE_DEAL_TAX", "TRANSACTION_DEAL_TAX", "COMMISSION_DEAL_MAKER",
      "COMMISSION_PROPERTY_SELLER", "TRANSMISSION_HINT_MAKER", "TRANSMISSION_PROPERTY_SELLER", "COMMISSION_REWARD", "SERVICE_YEARS_1", "SERVICE_DAYS_1", "SERVICE_YEARS_2",
      "SERVICE_DAYS_2", "SERVICE_YEARS_3", "SERVICE_DAYS_3", "SERVICE_YEARS_4", "SERVICE_DAYS_4", "TEMPORARY_CONTRACT_END_DAYS", "PROBATION_CONTRACT_END_DAYS", "COMMISSION_END_DAYS",
      "EMPLOYEE_BIRTHDAY_DAYS", "CUSTOMER_BIRTHDAY_DAYS", "LEAD_DELIVERE_START_TIME", "LEAD_DELIVERE_END_TIME", "SUPERINTENDENT_DOCUMENT_VALID_TIME", "SUPERINTENDENT_DOCUMENT_VALID_MONTHS",
      "APARTMENT_LIMIT", "PENALTY_INTEREST", "CREATOR_ID", "UPDATER_ID", "IS_ACTIVE", "IS_DELETED", "CREATED_AT", "UPDATED_AT", "CLAIMS_PERIOD", "LATE_PAYMENT_INTEREST", "PRICE_APPRAISAL_REPORT_FEE",
      "PRICE_APPRAISAL_BOOK_FEE", "FIXED_PROPERTY_RENT_PER_MONTH", "RENT_PROPERTY_DOCUMENT_EXPENSES", "RENT_PROPERTY_TAX_BASE", "FIXED_APARTMENT_RENT_PER_MONTH", "RENT_APARTMENT_DOCUMENT_EXPENSES",
      "RENT_APARTMENT_TAX_BASE", "RATE_PER_KILOMETER", "LEAD_DELIVERY_START_DAY", "LEAD_DELIVERY_END_DAY", "RENT_TENANT_APARTMENT_TAX_BASE", "RENT_TENANT_APARTMENT_DOCUMENT_EXPENSES", "RENT_TENANT_PROPERTY_TAX_BASE",
      "RENT_TENANT_PROPERTY_DOCUMENT_EXPENSES", "PRICE_APPRAISAL_REPORT_APARTMENT_DOCUMENT_CHARGES", "PRICE_APPRAISAL_BOOK_FEE_APARTMENT_DOCUMENT_CHARGES", "PRICE_APPRAISAL_REPORT_FEE_PROPERTY_DOCUMENT_CHARGES",
      "PRICE_APPRAISAL_BOOK_FEE_PROPERTY_DOCUMENT_CHARGES", "PRICE_NAVIGATOR_WEIGHT_1", "PRICE_NAVIGATOR_WEIGHT_2", "PRICE_NAVIGATOR_WEIGHT_3", "PRICE_NAVIGATOR_WEIGHT_4",
      "BRAND_COMPANY_NAME","BRAND_COMPANY_ID","BRAND_NAME","BRAND_ADDRESS","BRAND_POST_NUMBER","BRAND_CITY","BRAND_WEBSITE","BRAND_PHONE_NUMBER","BRAND_INVOICE_ADDRESS",
      "BRAND_INVOICE_POST_NUMBER","BRAND_INVOICE_CITY","BRAND_INVOICE_EMAIL","BRAND_INVOICE_OPERATOR","BRAND_INVOICE_E_ADDRESS","BRAND_INVOICE_OVT_ID","BRAND_BANK_DETAILS",
      "KAHISEVA_COMPANY_NAME","KAHISEVA_COMPANY_ID","KAHISEVA_NAME","KAHISEVA_ADDRESS","KAHISEVA_POST_NUMBER","KAHISEVA_CITY","KAHISEVA_WEBSITE","KAHISEVA_PHONE_NUMBER","KAHISEVA_INVOICE_ADDRESS",
      "KAHISEVA_INVOICE_POST_NUMBER","KAHISEVA_INVOICE_CITY","KAHISEVA_INVOICE_EMAIL","KAHISEVA_INVOICE_OPERATOR","KAHISEVA_INVOICE_E_ADDRESS","KAHISEVA_INVOICE_OVT_ID","KAHISEVA_BANK_DETAILS",
      "GLOBAL_FOUNDED_YEAR","GLOBAL_AGENTS","GLOBAL_COUNTRIES","GLOBAL_OFFICES","GLOBAL_WEBSITE",
      "LOCAL_FOUNDED_YEAR","LOCAL_WORKERS","LOCAL_OFFICES", "FACEBOOK", "LINKEDIN", "TWITTER", "MESSAGE_EMAIL"]
    keys + Setting.buy_setting_keys
  end

  def self.buy_setting_keys
    [ "SEARCHING_SERVICES_FIXED_FEE", "SEARCHING_SERVICES_PCT_FEE", "SEARCHING_SERVICES_VAT",
      "VISIT_ESTIMATE_SERVICES_FIXED_FEE", "VISIT_ESTIMATE_SERVICES_PCT_FEE", "VISIT_ESTIMATE_SERVICES_VAT",
      "NEGOTIATIONS_OFFER_TRAFFIC_SERVICES_FIXED_FEE", "NEGOTIATIONS_OFFER_TRAFFIC_SERVICES_PCT_FEE", "NEGOTIATIONS_OFFER_TRAFFIC_SERVICES_VAT",
      "MONITORING_CONTRACT_SERVICES_FIXED_FEE", "MONITORING_CONTRACT_SERVICES_PCT_FEE", "MONITORING_CONTRACT_SERVICES_VAT",
      "SEARCHING_SERVICES_PROPERTY_FIXED_FEE", "SEARCHING_SERVICES_PROPERTY_PCT_FEE", "SEARCHING_SERVICES_PROPERTY_VAT",
      "VISIT_ESTIMATE_SERVICES_PROPERTY_FIXED_FEE", "VISIT_ESTIMATE_SERVICES_PROPERTY_PCT_FEE", "VISIT_ESTIMATE_SERVICES_PROPERTY_VAT",
      "NEGOTIATIONS_OFFER_TRAFFIC_SERVICES_PROPERTY_FIXED_FEE", "NEGOTIATIONS_OFFER_TRAFFIC_SERVICES_PROPERTY_PCT_FEE", "NEGOTIATIONS_OFFER_TRAFFIC_SERVICES_PROPERTY_VAT",
      "MONITORING_CONTRACT_SERVICES_PROPERTY_FIXED_FEE", "MONITORING_CONTRACT_SERVICES_PROPERTY_PCT_FEE", "MONITORING_CONTRACT_SERVICES_PROPERTY_VAT",
      "BUYING_TOTAL_FIXED_FEE", "BUYING_TOTAL_PCT_FEE", "BUYING_DOCUMENT_CHARGES", "BUYING_DOCUMENT_CHARGES_VAT",
      "BUYING_TOTAL_REPORTS", "BUYING_REPORT_PRICE", "BUYING_REPORT_VAT",
      "BUYING_PROPERTY_TOTAL_FIXED_FEE", "BUYING_PROPERTY_TOTAL_PCT_FEE", "BUYING_PROPERTY_DOCUMENT_CHARGES", "BUYING_PROPERTY_DOCUMENT_CHARGES_VAT",
      "BUYING_PROPERTY_TOTAL_REPORTS", "BUYING_PROPERTY_REPORT_PRICE", "BUYING_PROPERTY_REPORT_VAT"]
  end

  def brand_address_full
    self.brand_address.to_s + "," + self.brand_post_number.to_s + " " + self.brand_city.to_s
  end
end
